#pragma once 

#define BUILD_VERSION_DATE "2017.08.06"
#define BUILD_VERSION_PER_DAY "6"
#define BUILD_VERSION_REVISION "25"
#define BUILD_VERSION_STRING "v" BUILD_VERSION_DATE "-" BUILD_VERSION_PER_DAY " (r" BUILD_VERSION_REVISION ")"
